### ISSUE TITLE
All loaded stacks not always available to select in recon window drop-down

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1277] opened 2022-01-28 16:03 UTC
### Summary

After changing what has been loaded in the tree-view, if you have an image at the top and either a second image or a dataset underneath then only the image will be available to select in the recon window drop-down. The problem can be resolved by deleting the first loaded image from the tree-view, or by loading a third image or dataset. The problem doesn't seem to occur on first launching MI, it is only if loaded data is deleted and added to the tree-view that the behaviour seems to begin.

### Steps To Reproduce

1) Load an image
2) Load a dataset or image
3) Delete the dataset or image from the tree-view
4) Load a dataset or image
5) Open the recon window and view the contents of the Data drop-down list

Note, if the second item loaded is a dataset then you need to keep the image that was loaded in step one for the behaviour to appear. If the second item loaded is an image then the behaviour seems to appear even when all the data in the tree-view is deleted and re-loaded.

### Expected Behaviour

All loaded stacks are available to select from the Data drop-down in the recon window.

### Current Behaviour

Only the first image in the tree-view is available to select from the Data drop-down in the recon window.

### Context

On current main.

**Comment by samtygier-stfc** [comment] 2022-01-28 17:05
I think this is fixed by #1276

**Comment by samtygier-stfc** [comment] 2022-02-02 12:04
I can't reproduce locally or on IDAaaS with current versions, so I thing #1276 fixed it.

**Closed by samtygier-stfc** 2022-02-02 12:04 UTC
Labels: Type: Bug
