### ISSUE TITLE
Intermittent AttributeError when using stack choice dialog

### ISSUE THREAD

**Issue by rbauststfc** [mantidproject/mantidimaging#1558] opened 2022-07-22 08:02 UTC
### Summary

Sometimes an AttributeError is thrown when the stack choice dialog is used.

### Steps To Reproduce

Further investigation is required to establish a clear sequence of steps that causes this problem - it occurs sometimes and not others when using the stack choice window. We need to collect more information to establish a pattern.

### Expected Behaviour

The stack choice dialog doesn't throw an error. 

### Current Behaviour

Sometimes an AttributeError complaining about a NoneType object is thrown - see log message below.

### Context

Current main.

### Failure Logs

```
File "mantidimaging/gui/windows/stack_choice/view.py", line 68, in <lambda> self.newDataButton.clicked.connect(lambda: self.presenter.notify(Notification.CHOOSE_NEW_DATA))
AttributeError: 'NoneType' object has no attribute 'notify'
```

**Comment by samtygier-stfc** [comment] 2022-11-24 11:12
I am going to close this for now as I can't reproduce the issue. Hopefully the clean up in #1637 will make it easier to debug if we see it again.

**Closed by samtygier-stfc** 2022-11-24 11:12 UTC
Labels: Type: Bug
